name       : python-dbus
version    : 1.2.4
release    : 11
source     :
    - https://dbus.freedesktop.org/releases/dbus-python/dbus-python-1.2.4.tar.gz : e2f1d6871f74fba23652e51d10873e54f71adab0525833c19bad9e99b1b2f9cc
license    : MIT
component  : 
    - system.base
    - ^python3-dbus : programming.python
summary    : D-Bus module for Python
description: |
    Easy access to dbus from Python
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(python3)
rundeps    :
    - ^python3-dbus : python3
patterns   :
    - ^python3-dbus : /usr/lib/python3*
setup      : |
    mkdir py2build && pushd py2build
        ../configure %CONFOPTS%
    popd

    mkdir py3build && pushd py3build
        PYTHON=python3 ../configure %CONFOPTS%
    popd
build      : |
    %make -C py2build
    %make -C py3build
install    : |
    %make_install -C py2build
    %make_install -C py3build
