name       : python-dbus
version    : 1.12.18
release    : 20
source     :
    - https://dbus.freedesktop.org/releases/dbus-python/dbus-python-1.2.18.tar.gz : 92bdd1e68b45596c833307a5ff4b217ee6929a1502f5341bae28fd120acf7260
license    : MIT
component  :
    - system.base
    - ^python3-dbus : programming.python
summary    : D-Bus module for Python
description: |
    Easy access to dbus from Python
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(python3)
rundeps    :
    - devel : python3-dbus
    - ^python3-dbus : python3
patterns   :
    - ^python3-dbus : /usr/lib/python3*
setup      : |
    mkdir py2build && pushd py2build
        ../configure %CONFOPTS% PYTHON=/usr/bin/python2
    popd

    mkdir py3build && pushd py3build
        ../configure %CONFOPTS% PYTHON=/usr/bin/python3
    popd
build      : |
    %make -C py2build
    %make -C py3build
install    : |
    %make_install -C py2build
    %make_install -C py3build
