name       : python-dbus
version    : 1.2.12
release    : 17
source     :
    - https://dbus.freedesktop.org/releases/dbus-python/dbus-python-1.2.12.tar.gz : cdd4de2c4f5e58f287b12013ed7b41dee81d503c8d0d2397c5bd2fb01badf260
license    : MIT
component  :
    - system.base
    - ^python3-dbus : programming.python
summary    : D-Bus module for Python
description: |
    Easy access to dbus from Python
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(python3)
rundeps    :
    - devel : python3-dbus
    - ^python3-dbus : python3
patterns   :
    - ^python3-dbus : /usr/lib/python3*
setup      : |
    mkdir py2build && pushd py2build
        ../configure %CONFOPTS%
    popd

    mkdir py3build && pushd py3build
        ../configure %CONFOPTS% PYTHON_VERSION=3
    popd
build      : |
    %make -C py2build
    %make -C py3build
install    : |
    %make_install -C py2build
    %make_install -C py3build
